export const customersData = [
  {
    id: "CUS-001",
    company: "PT Agri Nusantara",
    contactPerson: "Budi Santoso",
    email: "budi@agrinusantara.co.id",
    country: "Indonesia",
    region: "Southeast Asia",
    totalOrders: 12,
    totalVolume: "185 tons",
    totalRevenue: 78_200,
    lastOrder: "2026-03-05",
    status: "Active",
    tier: "Gold",
  },
  {
    id: "CUS-002",
    company: "Tata Seeds India",
    contactPerson: "Rajesh Kumar",
    email: "rajesh@tataseeds.in",
    country: "India",
    region: "South Asia",
    totalOrders: 8,
    totalVolume: "120 tons",
    totalRevenue: 54_000,
    lastOrder: "2026-02-25",
    status: "Active",
    tier: "Silver",
  },
  {
    id: "CUS-003",
    company: "AgriCorp Vietnam",
    contactPerson: "Nguyen Van Minh",
    email: "minh@agricorp.vn",
    country: "Vietnam",
    region: "Southeast Asia",
    totalOrders: 15,
    totalVolume: "210 tons",
    totalRevenue: 98_700,
    lastOrder: "2026-03-03",
    status: "Active",
    tier: "Platinum",
  },
  {
    id: "CUS-004",
    company: "Kenya Seed Co.",
    contactPerson: "James Ochieng",
    email: "james@kenyaseed.co.ke",
    country: "Kenya",
    region: "Africa",
    totalOrders: 5,
    totalVolume: "65 tons",
    totalRevenue: 26_000,
    lastOrder: "2026-03-01",
    status: "Active",
    tier: "Silver",
  },
  {
    id: "CUS-005",
    company: "Semillas del Sur",
    contactPerson: "Carlos Mendoza",
    email: "carlos@semillasdelsur.mx",
    country: "Mexico",
    region: "Latin America",
    totalOrders: 10,
    totalVolume: "155 tons",
    totalRevenue: 66_650,
    lastOrder: "2026-03-01",
    status: "Active",
    tier: "Gold",
  },
  {
    id: "CUS-006",
    company: "Myanmar Agro Ltd",
    contactPerson: "Aung Min Thein",
    email: "aung@myanmaragro.com",
    country: "Myanmar",
    region: "Southeast Asia",
    totalOrders: 4,
    totalVolume: "48 tons",
    totalRevenue: 22_080,
    lastOrder: "2026-02-28",
    status: "Active",
    tier: "Bronze",
  },
  {
    id: "CUS-007",
    company: "Bangladesh Seeds",
    contactPerson: "Mohammad Rahman",
    email: "rahman@bdseeds.com",
    country: "Bangladesh",
    region: "South Asia",
    totalOrders: 7,
    totalVolume: "95 tons",
    totalRevenue: 41_800,
    lastOrder: "2026-02-26",
    status: "Active",
    tier: "Silver",
  },
  {
    id: "CUS-008",
    company: "Thai Corn Trading",
    contactPerson: "Somchai Prasert",
    email: "somchai@thaicorn.co.th",
    country: "Thailand",
    region: "Southeast Asia",
    totalOrders: 9,
    totalVolume: "140 tons",
    totalRevenue: 65_800,
    lastOrder: "2026-02-24",
    status: "Active",
    tier: "Gold",
  },
  {
    id: "CUS-009",
    company: "Nigeria AgroChem",
    contactPerson: "Oluwaseun Adeyemi",
    email: "seun@nigeriaagro.ng",
    country: "Nigeria",
    region: "Africa",
    totalOrders: 6,
    totalVolume: "78 tons",
    totalRevenue: 31_980,
    lastOrder: "2026-02-22",
    status: "Active",
    tier: "Silver",
  },
  {
    id: "CUS-010",
    company: "Philippine Hybrid",
    contactPerson: "Maria Santos",
    email: "maria@phhybrid.com.ph",
    country: "Philippines",
    region: "Southeast Asia",
    totalOrders: 11,
    totalVolume: "165 tons",
    totalRevenue: 71_775,
    lastOrder: "2026-02-20",
    status: "Active",
    tier: "Gold",
  },
  {
    id: "CUS-011",
    company: "Tanzania Seeds Ltd",
    contactPerson: "Joseph Mwangi",
    email: "joseph@tzseeds.co.tz",
    country: "Tanzania",
    region: "Africa",
    totalOrders: 3,
    totalVolume: "35 tons",
    totalRevenue: 14_000,
    lastOrder: "2025-12-10",
    status: "Inactive",
    tier: "Bronze",
  },
  {
    id: "CUS-012",
    company: "Cambodia Agri Corp",
    contactPerson: "Sok Chanthy",
    email: "chanthy@cambodiaagri.kh",
    country: "Cambodia",
    region: "Southeast Asia",
    totalOrders: 2,
    totalVolume: "22 tons",
    totalRevenue: 9_900,
    lastOrder: "2025-11-15",
    status: "Prospect",
    tier: "—",
  },
];
