export const ordersData = [
  {
    id: "ORD-2601",
    customer: "PT Agri Nusantara",
    contactPerson: "Budi Santoso",
    variety: "CY-3088",
    quantity: "45 tons",
    unitPrice: "$420/ton",
    totalAmount: 18_900,
    destination: "Indonesia",
    port: "Tanjung Priok, Jakarta",
    status: "Shipped",
    paymentStatus: "Paid",
    orderDate: "2026-02-20",
    shipDate: "2026-03-05",
    eta: "2026-03-18",
  },
  {
    id: "ORD-2598",
    customer: "Tata Seeds India",
    contactPerson: "Rajesh Kumar",
    variety: "CY-2055",
    quantity: "32 tons",
    unitPrice: "$450/ton",
    totalAmount: 14_400,
    destination: "India",
    port: "Nhava Sheva, Mumbai",
    status: "Processing",
    paymentStatus: "Partial",
    orderDate: "2026-02-25",
    shipDate: "—",
    eta: "—",
  },
  {
    id: "ORD-2595",
    customer: "AgriCorp Vietnam",
    contactPerson: "Nguyen Van Minh",
    variety: "CY-4012",
    quantity: "28 tons",
    unitPrice: "$480/ton",
    totalAmount: 13_440,
    destination: "Vietnam",
    port: "Cat Lai, Ho Chi Minh",
    status: "Shipped",
    paymentStatus: "Paid",
    orderDate: "2026-02-18",
    shipDate: "2026-03-03",
    eta: "2026-03-12",
  },
  {
    id: "ORD-2592",
    customer: "Kenya Seed Co.",
    contactPerson: "James Ochieng",
    variety: "CY-1099",
    quantity: "18 tons",
    unitPrice: "$400/ton",
    totalAmount: 7_200,
    destination: "Kenya",
    port: "Mombasa",
    status: "Pending",
    paymentStatus: "Unpaid",
    orderDate: "2026-03-01",
    shipDate: "—",
    eta: "—",
  },
  {
    id: "ORD-2589",
    customer: "Semillas del Sur",
    contactPerson: "Carlos Mendoza",
    variety: "CY-3088",
    quantity: "55 tons",
    unitPrice: "$430/ton",
    totalAmount: 23_650,
    destination: "Mexico",
    port: "Manzanillo",
    status: "Shipped",
    paymentStatus: "Paid",
    orderDate: "2026-02-10",
    shipDate: "2026-03-01",
    eta: "2026-03-20",
  },
  {
    id: "ORD-2586",
    customer: "Myanmar Agro Ltd",
    contactPerson: "Aung Min Thein",
    variety: "CY-5021",
    quantity: "20 tons",
    unitPrice: "$460/ton",
    totalAmount: 9_200,
    destination: "Myanmar",
    port: "Yangon",
    status: "Processing",
    paymentStatus: "Partial",
    orderDate: "2026-02-28",
    shipDate: "—",
    eta: "—",
  },
  {
    id: "ORD-2583",
    customer: "Bangladesh Seeds",
    contactPerson: "Mohammad Rahman",
    variety: "CY-2055",
    quantity: "38 tons",
    unitPrice: "$440/ton",
    totalAmount: 16_720,
    destination: "Bangladesh",
    port: "Chittagong",
    status: "Delivered",
    paymentStatus: "Paid",
    orderDate: "2026-02-05",
    shipDate: "2026-02-26",
    eta: "2026-03-08",
  },
  {
    id: "ORD-2580",
    customer: "Thai Corn Trading",
    contactPerson: "Somchai Prasert",
    variety: "CY-4012",
    quantity: "42 tons",
    unitPrice: "$470/ton",
    totalAmount: 19_740,
    destination: "Thailand",
    port: "Laem Chabang",
    status: "Delivered",
    paymentStatus: "Paid",
    orderDate: "2026-01-28",
    shipDate: "2026-02-24",
    eta: "2026-03-02",
  },
  {
    id: "ORD-2577",
    customer: "Nigeria AgroChem",
    contactPerson: "Oluwaseun Adeyemi",
    variety: "CY-1099",
    quantity: "25 tons",
    unitPrice: "$410/ton",
    totalAmount: 10_250,
    destination: "Nigeria",
    port: "Apapa, Lagos",
    status: "Shipped",
    paymentStatus: "Paid",
    orderDate: "2026-02-08",
    shipDate: "2026-02-22",
    eta: "2026-03-15",
  },
  {
    id: "ORD-2574",
    customer: "Philippine Hybrid",
    contactPerson: "Maria Santos",
    variety: "CY-3041",
    quantity: "30 tons",
    unitPrice: "$435/ton",
    totalAmount: 13_050,
    destination: "Philippines",
    port: "Manila",
    status: "Delivered",
    paymentStatus: "Paid",
    orderDate: "2026-01-20",
    shipDate: "2026-02-20",
    eta: "2026-02-28",
  },
];
