export const broadcastsData = [
  {
    id: "BRC-001",
    title: "New Variety Alert: CYAN Titan 21 Now Available",
    channel: "LINE",
    type: "Product",
    audience: "All Friends",
    audienceSize: 12_400,
    status: "Sent",
    scheduledAt: "2026-03-03 09:00",
    openRate: "68%",
    clickRate: "12.5%",
  },
  {
    id: "BRC-002",
    title: "Weekly Market Corn Price Update",
    channel: "LINE",
    type: "Info",
    audience: "Dealers",
    audienceSize: 3_200,
    status: "Sent",
    scheduledAt: "2026-03-07 08:00",
    openRate: "82%",
    clickRate: "15.2%",
  },
  {
    id: "BRC-003",
    title: "Spring Planting Season Discount",
    channel: "LINE",
    type: "Promotion",
    audience: "All Friends",
    audienceSize: 12_400,
    status: "Sent",
    scheduledAt: "2026-03-01 10:00",
    openRate: "71%",
    clickRate: "18.3%",
  },
  {
    id: "BRC-004",
    title: "Drought-Tolerant Variety Guide",
    channel: "LINE",
    type: "Educational",
    audience: "Farmers",
    audienceSize: 8_600,
    status: "Sent",
    scheduledAt: "2026-02-25 09:00",
    openRate: "64%",
    clickRate: "9.8%",
  },
  {
    id: "BRC-005",
    title: "Monday Tips: Optimal Seed Spacing",
    channel: "LINE",
    type: "Educational",
    audience: "Farmers",
    audienceSize: 8_600,
    status: "Scheduled",
    scheduledAt: "2026-03-10 08:00",
    openRate: "—",
    clickRate: "—",
  },
  {
    id: "BRC-006",
    title: "March Inventory Clearance",
    channel: "LINE",
    type: "Promotion",
    audience: "Dealers",
    audienceSize: 3_200,
    status: "Scheduled",
    scheduledAt: "2026-03-12 10:00",
    openRate: "—",
    clickRate: "—",
  },
  {
    id: "BRC-007",
    title: "CY-3088 Success Story: Indonesia",
    channel: "LINE",
    type: "Product",
    audience: "All Friends",
    audienceSize: 12_400,
    status: "Draft",
    scheduledAt: "—",
    openRate: "—",
    clickRate: "—",
  },
  {
    id: "BRC-008",
    title: "Rainy Season Prep Checklist",
    channel: "LINE",
    type: "Educational",
    audience: "Farmers",
    audienceSize: 8_600,
    status: "Draft",
    scheduledAt: "—",
    openRate: "—",
    clickRate: "—",
  },
];
