export const varietiesData = [
  {
    id: "CY-3088",
    name: "CYAN Thunder 88",
    type: "Hybrid",
    maturity: "110 days",
    yieldPotential: "12.5 t/ha",
    traits: ["Drought tolerant", "High starch"],
    status: "Commercial",
    generation: "F8",
    region: "Tropical lowland",
    releaseYear: "2023",
  },
  {
    id: "CY-2055",
    name: "CYAN Gold 55",
    type: "Hybrid",
    maturity: "105 days",
    yieldPotential: "11.8 t/ha",
    traits: ["Rust resistant", "Early vigor"],
    status: "Commercial",
    generation: "F7",
    region: "Subtropical",
    releaseYear: "2022",
  },
  {
    id: "CY-4012",
    name: "CYAN Storm 12",
    type: "Hybrid",
    maturity: "115 days",
    yieldPotential: "13.2 t/ha",
    traits: ["High protein", "Lodging resistant"],
    status: "Commercial",
    generation: "F8",
    region: "Tropical highland",
    releaseYear: "2024",
  },
  {
    id: "CY-1099",
    name: "CYAN Blaze 99",
    type: "Hybrid",
    maturity: "100 days",
    yieldPotential: "10.5 t/ha",
    traits: ["Short duration", "Heat tolerant"],
    status: "Commercial",
    generation: "F6",
    region: "Arid/Semi-arid",
    releaseYear: "2021",
  },
  {
    id: "CY-5021",
    name: "CYAN Titan 21",
    type: "Hybrid",
    maturity: "120 days",
    yieldPotential: "14.0 t/ha",
    traits: ["High yield", "Stalk strength"],
    status: "Pre-commercial",
    generation: "F7",
    region: "Tropical lowland",
    releaseYear: "2025",
  },
  {
    id: "CY-3041",
    name: "CYAN Swift 41",
    type: "Hybrid",
    maturity: "95 days",
    yieldPotential: "9.8 t/ha",
    traits: ["Ultra-early", "Waterlogging tolerant"],
    status: "Commercial",
    generation: "F6",
    region: "Monsoon",
    releaseYear: "2023",
  },
  {
    id: "CY-6007",
    name: "CYAN Pearl 07",
    type: "OPV",
    maturity: "108 days",
    yieldPotential: "8.5 t/ha",
    traits: ["QPM", "Low-input adapted"],
    status: "Commercial",
    generation: "Syn-4",
    region: "Sub-Saharan Africa",
    releaseYear: "2020",
  },
  {
    id: "CY-7033",
    name: "CYAN Nova 33",
    type: "Hybrid",
    maturity: "112 days",
    yieldPotential: "12.0 t/ha",
    traits: ["Stem borer resistant", "Stay-green"],
    status: "Regional Trial",
    generation: "F5",
    region: "Southeast Asia",
    releaseYear: "—",
  },
  {
    id: "CY-8015",
    name: "CYAN Spark 15",
    type: "Hybrid",
    maturity: "118 days",
    yieldPotential: "13.5 t/ha",
    traits: ["Dual-purpose", "Silage quality"],
    status: "Testcross",
    generation: "F4",
    region: "Subtropical",
    releaseYear: "—",
  },
  {
    id: "CY-9002",
    name: "CYAN Dawn 02",
    type: "Inbred",
    maturity: "105 days",
    yieldPotential: "—",
    traits: ["Flint kernel", "Cold tolerant"],
    status: "Inbred Selection",
    generation: "S6",
    region: "Highland",
    releaseYear: "—",
  },
];
