export const contentData = [
  {
    id: "CNT-001",
    title: "CY-3088 Field Performance Showcase",
    type: "Video",
    format: "Reels / Short",
    duration: "0:45",
    channels: ["Instagram", "Facebook"],
    status: "Published",
    publishDate: "2026-03-06",
    reach: 45_200,
    engagement: 3_800,
  },
  {
    id: "CNT-002",
    title: "Seed Quality Testing Process",
    type: "Video",
    format: "Long-form",
    duration: "3:20",
    channels: ["Facebook", "LINE"],
    status: "Published",
    publishDate: "2026-03-04",
    reach: 38_100,
    engagement: 2_950,
  },
  {
    id: "CNT-003",
    title: "New Variety: CYAN Titan 21",
    type: "Text",
    format: "Broadcast",
    duration: "—",
    channels: ["LINE"],
    status: "Published",
    publishDate: "2026-03-03",
    reach: 12_400,
    engagement: 4_200,
  },
  {
    id: "CNT-004",
    title: "Farmer Testimonial — Indonesia",
    type: "Video",
    format: "Reels / Short",
    duration: "0:58",
    channels: ["Instagram"],
    status: "Published",
    publishDate: "2026-03-01",
    reach: 32_600,
    engagement: 2_100,
  },
  {
    id: "CNT-005",
    title: "Drought Tolerance Comparison",
    type: "Image",
    format: "Infographic",
    duration: "—",
    channels: ["Facebook", "Instagram"],
    status: "Published",
    publishDate: "2026-02-28",
    reach: 28_400,
    engagement: 1_800,
  },
  {
    id: "CNT-006",
    title: "March Promotion Banner",
    type: "Image",
    format: "Banner",
    duration: "—",
    channels: ["LINE", "Facebook"],
    status: "Scheduled",
    publishDate: "2026-03-10",
    reach: 0,
    engagement: 0,
  },
  {
    id: "CNT-007",
    title: "Planting Season Tips",
    type: "Video",
    format: "Reels / Short",
    duration: "0:30",
    channels: ["Instagram", "Facebook"],
    status: "Draft",
    publishDate: "—",
    reach: 0,
    engagement: 0,
  },
  {
    id: "CNT-008",
    title: "CY-2055 vs CY-4012 Yield Data",
    type: "Image",
    format: "Carousel",
    duration: "—",
    channels: ["Instagram"],
    status: "In Review",
    publishDate: "—",
    reach: 0,
    engagement: 0,
  },
  {
    id: "CNT-009",
    title: "Weekly Market Price Update",
    type: "Text",
    format: "Broadcast",
    duration: "—",
    channels: ["LINE"],
    status: "Scheduled",
    publishDate: "2026-03-11",
    reach: 0,
    engagement: 0,
  },
  {
    id: "CNT-010",
    title: "Harvest Season Behind-the-Scenes",
    type: "Video",
    format: "Long-form",
    duration: "5:12",
    channels: ["Facebook"],
    status: "Draft",
    publishDate: "—",
    reach: 0,
    engagement: 0,
  },
];
